#ifndef __GUIMyFrame1__
#define __GUIMyFrame1__

/**
@file
Subclass of MyFrame1, which is generated by wxFormBuilder.
*/

#include "GUI.h"

//// end generated include

/** Implementing MyFrame1 */
class GUIMyFrame1 : public MyFrame1
{
	protected:
		// Handlers for MyFrame1 events.
		void MainFormClose( wxCloseEvent& event );
		void WxPanel_Repaint( wxUpdateUIEvent& event );
		void Edit_FRx0_Update( wxCommandEvent& event );
		void Edit_FRy0_Update( wxCommandEvent& event );
		void Edit_FRx1_Update( wxCommandEvent& event );
		void Edit_FRy1_Update( wxCommandEvent& event );
		void ScrollBar_R_alpha_Update( wxScrollEvent& event );
		void RadioButton_R_Screen_Click( wxCommandEvent& event );
		void RadioButton_R_Graph_Click( wxCommandEvent& event );
		void Edit_TdX_Update( wxCommandEvent& event );
		void Edit_TdY_Update( wxCommandEvent& event );
		void Edit_Ax_start_Update( wxCommandEvent& event );
		void Edit_Ax_stop_Update( wxCommandEvent& event );
		void Choice_Selected_Function( wxCommandEvent& event );
		void Button_to_FrameRef_click( wxCommandEvent& event );
		void Button_Load_click( wxCommandEvent& event );
		void Button_Save_click( wxCommandEvent& event );
	public:
		/** Constructor */
		GUIMyFrame1( wxWindow* parent );
	//// end generated class members


};

#endif // __GUIMyFrame1__
